### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by vidishashah25** [nashfive/phone_number#3] opened 2019-05-31 17:09 UTC
Update README with description and documentation on how to use

**Comment by EngrEric** [comment] 2019-08-21 18:54
Yes, show the exposed APIs.
for e.g users should know what PhoneNumber.parse() or PhoneNumber.format() will return.

**Comment by nixoncode** [comment] 2019-08-24 16:39
This would be really helpful.

**Comment by nashfive** [comment] 2020-10-11 14:34
Duplicate of #10

**Closed by nashfive** 2020-10-11 14:34 UTC
Labels: enhancement
